### ISSUE TITLE
Kala 0.1 Meta Issue

### ISSUE THREAD

**Issue by mconcat** [kanon-io/kala#1]
- [ ] Interpreter
  - [ ] Core features
    - [ ] Environment Record
    - [ ] Detailed error handling
    - [ ] 
  - [ ] Improvements
    - [ ] IEEE754-2008 implementation
    - [ ] AST allocation optimization using bumpalo
    - [ ] Runtime optimization for Identifiers
    - [ ] Shortcut for top level declarations
  - [ ] Bindings
    - [ ] Cosmwasm 
- [ ] Transpiler
- [ ]
